steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=asia.gcr.io/$PROJECT_ID/cloudbuild-practice:$TAG_NAME'
      - '--tag=asia.gcr.io/$PROJECT_ID/cloudbuild-practice:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "asia.gcr.io/$PROJECT_ID/cloudbuild-practice:$TAG_NAME"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "asia.gcr.io/$PROJECT_ID/cloudbuild-practice:latest"]
