steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=asia.gcr.io/$PROJECT_ID/cloudbuild-practice:$TAG_NAME'
      - '--tag=asia.gcr.io/$PROJECT_ID/cloudbuild-practice:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "asia.gcr.io/$PROJECT_ID/cloudbuild-practice:$TAG_NAME"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "asia.gcr.io/$PROJECT_ID/cloudbuild-practice:latest"]
  # 開発環境のデプロイ
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - -c
      - './scripts/kustomize-apply.sh kubernetes/overlays/develop/'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=mycluster'
  # 本番環境のデプロイ
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - -c
      - './scripts/kustomize-apply.sh kubernetes/overlays/production/'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=mycluster'
